vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set mouse=")
vim.cmd("set number")
vim.cmd("set relativenumber")

vim.keymap.set('n', 'gn', ':bnext<CR>')
vim.keymap.set('n', 'gp', ':bprev<CR>')
vim.keymap.set('n', '<leader>rr', ':w<CR>:so %<CR>')
